logout:
    path: /logout


app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

db_doc_routing:
    resource: '@ForceDBDocBundle/Resources/config/routing.yaml'
